<h2>Hotels</h2>

<table class="table table-striped">
    <thead>
    <tr>
        <th>Name</th>
        <th>Number of users checked in</th>
        <th>Users</th>
    </tr>
    </thead>
<?php
/** @var \App\Domain\Model\Building $building */
foreach ($buildings as $building): ?>
<tr>
    <td><?= $building->name ?></td>
    <td><?= count($building->checkedIn) ?></td>
    <td><?= implode(', ', $building->checkedIn) ?></td>
</tr>
<?php endforeach; ?>
</table>

<br />
<br />
<hr />
<br />
<br />

<h2>Create building</h2>

<form action="/" method="post">
    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" id="name" name="name" class="form-control">
        </div>
    </div>
    <div class="text-right">
        <button type="submit" name="createBuilding" class="btn btn-primary mb-2">Create building</button>
    </div>
</form>

<?php if(count($buildings)): ?>

<br />
<br />
<hr />
<br />
<br />

<h2>Check in</h2>

<form action="/" method="post">
    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" id="name" name="name" class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <label for="building" class="col-sm-2 col-form-label">Building</label>
        <div class="col-sm-10">
            <select id="building" class="form-control" name="building">
                <option></option>
                <?php
                /** @var \App\Domain\Model\Building $building */
                foreach ($buildings as $building): ?>
                    <option value="<?= $building->id ?>"><?= $building->name ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="text-right">
        <button type="submit" name="checkIn" class="btn btn-primary mb-2">Check in</button>
    </div>
</form>

<br />
<br />
<hr />
<br />
<br />

<h2>Check out</h2>

<form action="/" method="post">
    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" id="name" name="name" class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <label for="building" class="col-sm-2 col-form-label">Building</label>
        <div class="col-sm-10">
            <select id="building" class="form-control" name="building">
                <option></option>
                <?php
                /** @var \App\Domain\Model\Building $building */
                foreach ($buildings as $building): ?>
                    <option value="<?= $building->id ?>"><?= $building->name ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="text-right">
        <button type="submit" name="checkOut" class="btn btn-primary mb-2">Check out</button>
    </div>
</form>

<br />
<br />
<hr />
<br />
<br />

<h2>Rename Hotel</h2>

<form action="/" method="post">
    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">New name</label>
        <div class="col-sm-10">
            <input type="text" id="name" name="name" class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <label for="building" class="col-sm-2 col-form-label">Building</label>
        <div class="col-sm-10">
            <select id="building" class="form-control" name="building">
                <option></option>
                <?php
                /** @var \App\Domain\Model\Building $building */
                foreach ($buildings as $building): ?>
                    <option value="<?= $building->id ?>"><?= $building->name ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="text-right">
        <button type="submit" name="renameBuilding" class="btn btn-warning mb-2">Rename</button>
    </div>
</form>

<h2>Demolish Hotel</h2>

<form action="/" method="post">
    <div class="form-group row">
        <label for="building" class="col-sm-2 col-form-label">Building</label>
        <div class="col-sm-10">
            <select id="building" class="form-control" name="building">
                <option></option>
                <?php
                /** @var \App\Domain\Model\Building $building */
                foreach ($buildings as $building): ?>
                    <option value="<?= $building->id ?>"><?= $building->name ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="text-right">
        <button type="submit" name="deleteBuilding" class="btn btn-danger mb-2">Demolish</button>
    </div>
</form>

<br />
<br />
<hr />
<br />
<br />

<br/>
<br/>
<br/>
<?php endif; ?>