version: '3.8'

x-templates:
  default-variables: &default-variables
    TZ: Europe/Berlin
  default-service: &default-service
    restart: unless-stopped
    tty: true
    stdin_open: true
    init: true
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      <<: *default-variables
  as-current-user: &as-current-user
    user: ${UID:-1000}:${GID:-1000}

services:
  db:
    <<: *default-service
    image: postgres:14-alpine
    container_name: event-source-db
    environment:
      <<: *default-variables
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    working_dir: "/app"
    ports:
      - "5432:5432"
    volumes:
      - ./:/app
      - db-data:/var/lib/postgresql/data
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  db-data:
    driver: local